# Site settings
title: Matt Romein
email: seth@channel.studio
description: > 
  Matt Romein is an artist and performer working at the intersection of live performance, generative computer art, and multi-media installation. Originally trained as an actor, he has worked in NYC’s downtown theater and dance community as a sound and video designer while also making his own technology-centric live performances.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matt-romein.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: polyrhythmatic

logo: "/assets/og_image.jpg"

# Build settings
markdown: kramdown

include: 
  - _pages

collections:
  projects:
    output: true

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-sitemap
