# Site settings
title: Matt Romein
email: seth@channel.studio
description: > 
  Some copy about Matt Romein
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://matt-romein.com/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: polyrhythmatic

logo: "/assets/logo.png"

# Build settings
markdown: kramdown

include: 
  - _pages

collections:
  projects:
    output: true

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-sitemap
